<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="newsletter">
    <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Newsletter') ?> </strong></div>
    <div class="block-content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="label-text">
                <span><?php /* @escapeNotVerified */ echo __('Sign up now to receive information on new arrivals, brands and special offers.') ?></span>
            </div>
            <div class="field newsletter">
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Email address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
                </div>
                <div class="actions">
                    <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                        <span><?php /* @escapeNotVerified */ echo __('<span class="fa fa-arrow-right"> </span>') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
