<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
$html = '';
$id = $block->getIdModifier() ? '-' . $block->getIdModifier() : time();
?>
<div class="header-links-wrapper">
    <div class="custom-group header-links" id="header-links<?php echo $id?>">
        <div class="actions dropdown options header-links-options">
            <div class="action toggle switcher-trigger" id="header-links-trigger<?php echo $id?>">
                <i class="fa fa-user"> </i>
            </div>
            <ul class="dropdown header-links-dropdown" data-mage-init='{"dropdownDialog":{
            "appendTo":"#header-links<?php echo $id?> > .options",
            "triggerTarget":"#header-links-trigger<?php echo $id?>",
            "closeOnMouseLeave": false,
            "triggerClass":"active",
            "parentClass":"active",
            "buttons":null}}'>
                <?php
                foreach ($this->getLinks() as $link) {
                    $html .= $this->renderLink($link);
                }
                echo $html;
                ?>
            </ul>
        </div>
    </div>
</div>




