<div id="ves-header"class="ves-header">
	<div class="grid-02">
		<?php echo $this->getChildHtml('skipToContent'); ?>
		<?php echo $this->getChildHtml("logo"); ?>
	</div>
	<div class="grid-07">
		<?php echo $this->getChildHtml('ves_navigation'); ?>
	</div>
	<div class="grid-03">
		<?php echo $this->getChildHtml('minicart'); ?>
		
		<div class="header-links-wrapper">
			<?php echo $this->getChildHtml('top_links') ?>
		</div>

		<div class="setting-wrapper">
			<?php echo $this->getChildHtml('setting_links') ?>
		</div>

		<?php echo $this->getChildHtml("topSearch"); ?>
	</div>
</div>

