<?php
use Magento\Framework\App\Action\Action;
$_vesHelper = $this->helper('Ves\Productlist\Helper\Data');
$_imgHelper = $this->helper('Ves\Productlist\Helper\Image');
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$blockId = rand().time();
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$html = $classes = '';
$tabId = 'productlist-'.$blockId;

// General Settings
$widget_title = $this->getConfig('widget_title');
$addition_class = $this->getConfig('addition_class');
$cmsblock = $this->getConfig('cmsblock');
$pretext_html = $this->getConfig('pretext_html');
if($cmsblock === 'pretext_html'){
    $html = base64_decode($pretext_html);
}elseif($cmsblock!=''){
    $html = $this->getCmsBlockModel()->load($cmsblock)->getContent();
}
$html = $_vesHelper->filter($html);


// Tab Settings
$number_item = $this->getConfig('number_item',12);
$enable_animate_tab = $this->getConfig('enable_animate_tab');
$animation_speed = (int)$this->getConfig('animation_speed',"slow");
$collapsible = $this->getConfig('collapsible');
$cycle = $this->getConfig('cycle',1000);
$default_tab = (int)$this->getConfig('default_tab',0);
$transition_in = $this->getConfig('transition_in',"fadeIn");
$transition_in_easing = $this->getConfig('transition_in_easing',"swing");
$transition_out = $this->getConfig('transition_out',"fadeOut");
$transition_out_easing = $this->getConfig('transition_out_easing',"swing");
$event = $this->getConfig('event',"click");
$defaultTabId = '';


// Item Settings
$height_type = $this->getConfig('height_type');
$custom_item_height = (int)(str_replace("px","",$this->getConfig('custom_item_height', "")));
$show_name_single_line = $this->getConfig('show_name_single_line');
if($show_name_single_line){
    $classes .= ' single-line-name';
}


// OWL Carousel
$number_item_percolumn = (int)$this->getConfig('number_item_percolumn',200);
$large_max_items = (int)$this->getConfig('large_max_items',6);
$large_items = (int)$this->getConfig('large_items',5);
$portrait_items = (int)$this->getConfig('portrait_items',4);
$tablet_items = (int)$this->getConfig('tablet_items',4);
$tablet_small_items = (int)$this->getConfig('tablet_small_items',2);
$mobile_items = (int)$this->getConfig('mobile_items',1);
$autoplay = $this->getConfig('autoplay');
$autoplay_timeout = (int)$this->getConfig('autoplay_timeout',3000);
$dots = $this->getConfig('dots');
$nav = $this->getConfig('nav');
$nav_next = $this->getConfig('nav_next');
$nav_pre = $this->getConfig('nav_pre');
$rtl = $this->getConfig('rtl',false);
$loop = $this->getConfig('loop');
$ajaxBlockId = 'productlist-owlcarousel-'.$blockId;

// Convert collection to multiple row
// Default column
$column = 13;
$tabs = $this->getTabs();
foreach ($tabs as $k => $tab) {
    if(!$tab['ajax_type']){
        $collection = $this->getProductsBySource($tab['source_id']);
        $_productCollection = [];
        $total = $collection->count();
        // if($total%$number_item_percolumn == 0){
        //     $column = $total/$number_item_percolumn;
        // }else{
        //     $column = floor($total/$number_item_percolumn)+1;
        // }
        // if($column<$large_max_items) $column = $large_max_items;
        $i = $x = 0;
        foreach ($collection as $_product) {
            if($i<$column){
                $i++;
            }else{
                $i = 1;
                $x++;
            }
            $_productCollection[$i][$x] = $_product;
        }
        $tabs[$k]['productCollection'] = $collection;
        $tabs[$k]['productCount'] = $total;
        if($total == 0) unset($tabs[$k]);
    }
    if(isset($tabs[$k])){
        $tabs[$k]['id'] = str_replace('_','-','productlist-'.$tab['source_id'].'-'.rand().time());
        if(isset($tabs[$k]['position']) && $default_tab && $tabs[$k]['position'] == $default_tab){
            $defaultTabId = 'tab-'.$tabs[$k]['id'];
        }
    }
}
$data = $this->getData();
?>

<!-- a -->


<nav id="sidebar" class="active">
    <div class="sidebar-header">
        <h3>Kala & Mann</h3>
    </div>
    <ul class="list-unstyled components">
        <li>
            <a href="#home">Home</a>
        </li>
        <li>
            <a href="#about">About Us</a>
        </li>
        <li>
            <a href="#gallery">Gallery</a>
        </li>
        <li>
            <a href="#contact">Contact Us</a>
        </li>
    </ul>
    <div class="navbar-header">
        <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
            <i class="fas fa-bars"></i>
        </button>
    </div>
</nav>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="#">Sign in</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Cart</a>
            </li>
        </ul>
    </div>
</nav>
<header>
    <div class="container">
        <h1 class="logo"><strong>KALA & MANN</strong></h1>

        <!-- Set up your HTML -->
        <div class="owl-carousel" id="gallery1">
            <div> <img class="actual" src="<?php echo $block->getUrl("pub/media/img/")?>Actual1.JPG"> </div>
            <div> <img class="actual" src="<?php echo $block->getUrl("pub/media/img/")?>Actual2.jpg"> </div>
        </div>

        <div class="social-buttons">
            <a href="#">
                <img src="<?php echo $block->getUrl("pub/media/img/")?>facebook.png">
            </a>
            <a href="#">
                <img src="<?php echo $block->getUrl("pub/media/img/")?>twitter.png">
            </a>
            <a href="#">
                <img src="<?php echo $block->getUrl("pub/media/img/")?>linkedin.png">
            </a>
            <a href="#">
                <img src="<?php echo $block->getUrl("pub/media/img/")?>instagram.png">
            </a>
            <a href="#">
                <img src="<?php echo $block->getUrl("pub/media/img/")?>pinterest.png">
            </a>
        </div>
    </div>
</header>
<div class="block" id="about">
    <div class="container about-us">
        <h1>About us</h1>
        <p class="margin-b">
            <p>At Kala & Mann we connect appreciators of art and design with creators of uniquely designed or handmade works that will enrich your living and working spaces and enlarge your sense of beauty and joy.</p>
            <p>The purpose of our company is to provide to you the most exclusive and unique pieces of art from the young and emerging talents from all over India. Kala & Mann enables upcoming artists to showcase their works to a worldwide audience that appreciates original art and offers the potential to own an exclusive piece created by, what could be, the next Pablo Picasso!</p>
            <p>These specially chosen individuals have to fulfil a number of criteria to satisfy our specifications in the area of handmade production, quality of the material used and best quality finishes. To meet this specification we control and observe the production standards on a permanent basis (see our blog page to follow our travels throughout India) and thus create one off pieces of art with a long lasting high value and outstanding quality.</p>
            <p>Kala & Mann stock only a small collection of artwork showcasing fine art in the form of Paintings, Sculpture and Installations. The online gallery provides a platform to view and procure handpicked original pieces but we also commission artworks for both private and corporate collections.</p>
            
        </p>
    </div>
</div>
<div class="block" id="gallery">
    <div class="container">
        <h1 class="gallery-h1">Gallery</h1>
        <p class="subtitle">Discover all our artworks</p>
        <div class="owl-carousel" id="gallery2">
            <div>
                <div class="block-img">
                    <img class="showcase-img" src="<?php echo $block->getUrl("pub/media/img/")?>Example1.jpg" alt="">
                    <div class="block-text">
                        <div class="row row-conformity">
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <p class="title"> Julie Susset </p>
                                <p class="category" href="#" title="Banana" itemprop="url"> Banana </p>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <p class="price">1 500 €</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="block-img">
                    <img class="showcase-img" src="<?php echo $block->getUrl("pub/media/img/")?>Example2.jpg" alt="">
                    <div class="block-text">
                        <div class="row row-conformity">
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <p class="title"> Julie Susset </p>
                                <p class="category" href="#" title="Banana" itemprop="url"> Banana </p>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <p class="price">1 500 €</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
            <div class="block-img">
                <img class="showcase-img" src="<?php echo $block->getUrl("pub/media/img/")?>Example3.jpg" alt="">
                <div class="block-text">
                    <div class="row row-conformity">
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                            <p class="title"> Julie Susset </p>
                            <p class="category" href="#" title="Banana" itemprop="url"> Banana </p>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                            <p class="price">1 500 €</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            <div>
                <div class="block-img">
                    <img class="showcase-img" src="<?php echo $block->getUrl("pub/media/img/")?>Example4.jpg" alt="">
                    <div class="block-text">
                        <div class="row row-conformity">
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <p class="title"> Julie Susset </p>
                                <p class="category" href="#" title="Banana" itemprop="url"> Banana </p>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <p class="price">1 500 €</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="block-img">
                    <img class="showcase-img" src="<?php echo $block->getUrl("pub/media/img/")?>Example5.jpg" alt="">
                    <div class="block-text">
                        <div class="row row-conformity">
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <p class="title"> Julie Susset </p>
                                <p class="category" href="#" title="Banana" itemprop="url"> Banana </p>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <p class="price">1 500 €</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>
</div>
<footer id="contact">
    <div class="container">
        <h1>Contact us</h1>
        <p class="margin-b">
            <div class="row">
                <div class="col-md-4 center bottom-offset">
                    <strong>Business Number:</strong><br>
                    0330 660 0323
                </div>
                <div class="col-md-4 center bottom-offset">
                    <strong>The business address is:</strong><br>
                    Kala & Mann Ltd<br>
                    3 St.Chads Court<br>
                    School Lane<br>
                    Rochdale
                </div>
                <div class="col-md-4 center bottom-offset">
                    <strong>Business Email:</strong><br>
                    <a href="mailto: sales@kalaandmann.com">sales@kalaandmann.com</a>
                </div>
            </div>
        </p>
    </div>

    <div class="container-fluid">
        <div class="row">
            <iframe class="gmap" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2366.8694048245493!2d-2.1556499251294143!3d53.61363220513797!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487bb943448d5959%3A0x20b63f1774d3fc34!2s3+St+Chad&#39;s+Cl%2C+Rochdale+OL16+1FG%2C+UK!5e0!3m2!1sen!2sua!4v1526564421679" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>
</footer>







    <?php if(count($tabs)>0){ ?>
    <div id="easytab-<?php echo $blockId ?>" class="block-img"  >
       
       
        <?php foreach ($tabs as $k => $tab) { ?>
       
            <?php
            $classTmp = 'owl-carousel';
            if(!isset($tab['productCount']) && !isset($tab['productCount'])){
                $classTmp = 'owl-carousel';
            } ?>
                <?php
                if(isset($tab['productCount']) && $tab['productCount']>0){
                    $collection = $tab['productCollection'];
                    ?>
                    <?php // Product List ?>
                    <?php
                    $data['collection'] = $collection;
                    echo $this->getProductHtml($data); ?>
                    <?php } ?>

                <?php // Custom Navigation ?>
            <?php /* ?>
            <div class="carousel-controls123">
                <a class="owl-left" href="javscript:void(0);">
                    <span class="fa fa-angle-left">Prev</span>
                </a>
                <a class="owl-right" href="javscript:void(0);">
                    <span class="fa fa-angle-right">Next</span>
                </a>
            </div>
            <?php */ ?>

        <?php } ?>
</div>


<script type="text/javascript">
    require([
        'jquery',
        'Ves_Productlist/js/jquery.easytabs.min',
        'Ves_Productlist/js/productlist',
        ], function () {
            var ajaxUrl = "<?php echo $this->getAjaxUrl() ?>";
            easyTabInit("<?php echo '#easytab-'.$blockId ?>").bind("easytabs:before",function(e, $clicked, $targetPanel, settings) {
                jQuery($targetPanel.selector).addClass("paneltab");
                equalHeight($targetPanel.selector);
            }).bind("easytabs:after",function(e, $clicked, $targetPanel, settings) {
                jQuery($targetPanel.selector).removeClass("paneltab");
            });
            <?php
            $conditionProductIdss = $this->getProductsByCondition()->getAllIds();
            $widgetData = $this->getData();
            unset($widgetData['pretext_html']);
            unset($widgetData['tabs']);
            unset($widgetData['conditions_encoded']);
            ?>
            <?php foreach ($tabs as $_tab) { ?>
                <?php if(isset($_tab['ajax_type']) && $_tab['ajax_type'] == 0){ ?>
                    owlCarouselInit("<?php echo '#'.$ajaxBlockId ?>", "<?php echo '#'.$_tab['id'].' .owl-carousel' ?>", "");
                    <?php } ?>
                    <?php
                    $data = [];
                    $data = $widgetData;
                    $data['ajaxBlockId'] = $ajaxBlockId;
                    $data['number_item'] = $widgetData['number_item'];
                    $data['tab'] = $_tab;
                    $data['conditionProductIds'] = json_encode($conditionProductIdss);
                    ?>
                    <?php if(isset($_tab['ajax_type']) && $_tab['ajax_type'] == 1){ ?>
                        ajaxProducts(<?php echo json_encode($data) ?>, ajaxUrl);
                        <?php } ?>
                        <?php if(isset($_tab['ajax_type']) && $_tab['ajax_type'] == 2){ ?>
                            ajaxClickProduct(<?php echo json_encode($data) ?>, ajaxUrl);
                            <?php } ?>
                            <?php } ?>


                    jQuery('#sidebarCollapse').on('click', function () {
                        jQuery('#sidebar').toggleClass('active');
                    });

                    jQuery(document).ready(function(){
                        jQuery('#gallery1').owlCarousel({
                            nav: true,
                            navText: ["←","→"],
                            loop:true,
                            items:1,
                            margin:0,
                            stagePadding:0,
                            smartSpeed:450,
                            autoHeight:true,
                            autoplay:true,
                            autoplayTimeout:4000,
                            autoplayHoverPause:true,
                            responsive:{
                                0:{

                                }
                            }
                        });
                        jQuery('#gallery2').owlCarousel({
                            nav: true,
                            navText: ["<span aria-label=\"Previous\">←</span>","<span aria-label=\"Next\">→</span>"],
                            items:2,
                            margin:50,
                            stagePadding:0,
                            smartSpeed:450,
                            center: true,
                            autoplay:false,
                            autoHeight:true,
                            responsive:{
                                0:{
                                    items:1,
                                    center: false,
                                    nav: false,
                                    margin:0,
                                },
                                600:{
                                    items:2
                                },
                                1000:{
                                    items:2
                                }
                            }
                        });

                        jQuery(document).on('click', 'a[href^="#"]', function (event) {
                            event.preventDefault();
                            jQuery('#sidebarCollapse').click();

                            jQuery('html, body').animate({
                                scrollTop: jQuery(jQuery.attr(this, 'href')).offset().top
                            }, 500);
                        });
                    });





                        });
            </script>
    <?php } ?>
