<?php
use Magento\Framework\App\Action\Action;
$data = $this->helper('Ves\Productlist\Helper\Data');
$_imgHelper = $this->helper('Ves\Productlist\Helper\Image');
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$blockId = rand().time();
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$classes = '';

// Item Settings
$custom_item_height = '';
$height_type = $this->getConfig('height_type');
if($height_type == 'custom'){
    $custom_item_height = (int)(str_replace("px","",$this->getConfig('custom_item_height', "")));
}
$show_image = $this->getConfig('show_image');
$aspect_ratio = $this->getConfig('aspect_ratio');
$image_width = $this->getConfig('image_width',500);
$image_height = (int)$this->getConfig('image_height');
$alt_image = $this->getConfig('alt_image');
$alt_image_column = $this->getConfig('alt_image_column','position');
$alt_image_column_value = $this->getConfig('alt_image_column_value',2);
//If image width is not specified, use default values
if ($image_width <= 0){
    $image_width = 300;
    $image_height = 300;
}
$catViewKeepFrame = TRUE; 
if($aspect_ratio){
    $image_height = 0;
    $catViewKeepFrame = FALSE;
}
if ($data->getCoreRegistry()->registry('catViewKeepFrame') === NULL){
    $data->getCoreRegistry()->register('catViewKeepFrame', $catViewKeepFrame);
}

$show_name = $this->getConfig('show_name');
$show_name_single_line = $this->getConfig('show_name_single_line');
if($show_name_single_line){
    $classes .= ' single-line-name';
}
$show_short_description = $this->getConfig('show_short_description');
$short_max_char = (int)$this->getConfig('short_max_char',100);
$show_learnmore = $this->getConfig('show_learnmore');
$show_price = $this->getConfig('show_price');
$show_review = $this->getConfig('show_review');
$show_compare = $this->getConfig('show_compare');
$compare_format = $this->getConfig('compare_format_type');
$compare_text = $this->getConfig('compare_format_text');
$compare_class = $this->getConfig('compare_format_class');
$compareText = '<span>'.$compare_text.'</span>';
$compareIcon = '<i class="'.$compare_class.'"></i>';
$compareHtml = '';
if((!$compare_format || $compare_format == 'text') && $compare_text){ // Only Text
    $compareHtml = $compareText;
}elseif($compare_format == 'icon'){ // Only Icon
    $compareHtml = $compareIcon;
}elseif($compare_format == 'icon-text'){ // Icon, Text
    $compareHtml = $compareIcon.$compareText;
}elseif($compare_format == 'text-icon'){ // Text, Icon
    $compareHtml = $compareText.$compareIcon;
}

$show_wishlist = $this->getConfig('show_wishlist');
$wishlist_format = $this->getConfig('wishlist_format_type');
$wishlist_text = $this->getConfig('wishlist_format_text');
$wishlist_class = $this->getConfig('wishlist_format_class');
$wishlistText = '<span>'.$wishlist_text.'</span>';
$wishlistIcon = '<i class="'.$wishlist_class.'"></i>';
$wishlistHtml = '';
if((!$wishlist_format || $wishlist_format == 'text') && $wishlist_text){ // Only Text
    $wishlistHtml = $wishlistText;
}elseif($wishlist_format == 'icon'){ // Only Icon
    $wishlistHtml = $wishlistIcon;
}elseif($wishlist_format == 'icon-text'){ // Icon, Text
    $wishlistHtml = $wishlistIcon.$wishlistText;
}elseif($wishlist_format == 'text-icon'){ // Text, Icon
    $wishlistHtml = $wishlistText.$wishlistIcon;
}

$show_countdowntimer = $this->getConfig('show_countdowntimer');
$show_new_label = $this->getConfig('show_new_label');
$show_sale_label = $this->getConfig('show_sale_label');

$show_addtocart = $this->getConfig('show_addtocart');
$addtocart_popup_width = $this->getConfig('addtocart_popup_width');
$addtocart_popup_height = $this->getConfig('addtocart_popup_height');
$addtocart_format = $this->getConfig('addtocart_format_type');
$addtocart_text = $this->getConfig('addtocart_format_text');
$addtocart_class = $this->getConfig('addtocart_format_class');
$addtocartText = '<span>'.$addtocart_text.'</span>';
$addtocartIcon = '<i class="'.$addtocart_class.'"></i>';
$addToCartHtml = '';
if((!$addtocart_format || $addtocart_format == 'text') && $addtocart_text){ // Only Text
    $addToCartHtml = $addtocartText;
}elseif($addtocart_format == 'icon'){ // Only Icon
    $addToCartHtml = $addtocartIcon;
}elseif($addtocart_format == 'icon-text'){ // Icon, Text
    $addToCartHtml = $addtocartIcon.$addtocartText;
}elseif($addtocart_format == 'text-icon'){ // Text, Icon
    $addToCartHtml = $addtocart_text.$addtocartIcon;
}

$addtocart_popup_width = $this->getConfig('addtocart_popup_width');
$addtocart_popup_height = $this->getConfig('addtocart_popup_height');
$show_quickview = $this->getConfig('show_quickview');
$quickview_popup_width = $this->getConfig('quickview_popup_width',600);
$quickview_popup_height = $this->getConfig('quickview_popup_height',600);
$quickview_format = $this->getConfig('quickview_format_type');
$quickview_text = $this->getConfig('quickview_format_text');
$quickview_class = $this->getConfig('quickview_format_class');
$quickviewText = '<span>'.$quickview_text.'</span>';
$quickviewIcon = '<i class="'.$quickview_class.'"></i>';
$quickviewtHtml = '';
if((!$quickview_format || $quickview_format == 'text') && $quickview_text){ // Only Text
    $quickviewtHtml = $quickviewText;
}elseif($quickview_format == 'icon'){ // Only Icon
    $quickviewtHtml = $quickviewIcon;
}elseif($quickview_format == 'icon-text'){ // Icon, Text
    $quickviewtHtml = $quickviewIcon.$quickviewText;
}elseif($quickview_format == 'text-icon'){ // Text, Icon
    $quickviewtHtml = $quickviewText.$quickviewIcon;
}

$collection = $this->getData('collection');
?>

    <?php foreach($collection as $_product){ ?>
    <?php $productId = time().rand(); ?>
    <div class="product-item-info block-img" <?php if($custom_item_height){ ?>style="height:<?php echo $custom_item_height.'px' ?>"<?php } ?>>

    <div class="product-image">
        <div class="product-img">
            <?php // Product Image ?>
            <?php if($show_image){ ?>
            <?php
            $_image = $_imgHelper->getImg($_product, $image_width, $image_height, 'product_page_image_medium');
            ?>
            <?php if($_image){ ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_image->getLabel() ?>" class="product-item-photo animsition-link"  
  >
                <img src="<?php echo $_image->getUrl('image'); ?>" alt="<?php echo $_image->getLabel() ?>" class="showcase-img" />
            </a>
            <?php } ?>
            <?php if($alt_image){ ?>
            <?php
            $_altImg = $_imgHelper->getAltImgHtml($_product, $image_width, $image_height, 'product_page_image_medium', $alt_image_column, $alt_image_column_value);
            ?>
            <?php if($_altImg){ ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_altImg->getLabel() ?>" class="hover-image showcase-img animsition-link" data-animsition-out-class="fade-out-right">
                <img src="<?php echo $_altImg->getUrl(); ?>" alt="<?php echo $_altImg->getLabel() ?>" />
            </a>
            <?php } ?>
            <?php } ?>
            <?php } ?>


            <div class="block-text gallery-text">
                
                        <div class="row row-conformity">
                            <?php // Review ?>
                <?php if($show_review){ ?>
                <?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
                <?php } ?>

                <?php // Name ?>
                <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                <?php if($show_name){ ?>
                            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-xl-8">
                                <a class="product-item-link title" href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                                <p title="Banana" itemprop="url"> Banana </p>
                            </div>
                            <?php } ?>
                            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
                                <?php if($show_price){ ?> 
        <?php echo $block->getProductPrice($_product) ?>
        <?php } ?>
                            </div>
                        </div>
            </div>



        </div>
    

</div>



</div>
<?php } ?>
<?php // End Product Information ?>
