<?php
use Magento\Framework\App\Action\Action;
$_vesHelper = $this->helper('Ves\Productlist\Helper\Data');
$_imgHelper = $this->helper('Ves\Productlist\Helper\Image');
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$blockId = rand().time();
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$html = $classes = '';
$tabId = 'productlist-'.$blockId;

// General Settings
$widget_title = $this->getConfig('widget_title');
$addition_class = $this->getConfig('addition_class');
$cmsblock = $this->getConfig('cmsblock');
$pretext_html = $this->getConfig('pretext_html');
if($cmsblock === 'pretext_html'){
    $html = base64_decode($pretext_html);
}elseif($cmsblock!=''){
    $html = $this->getCmsBlockModel()->load($cmsblock)->getContent();
}
$html = $_vesHelper->filter($html);


// Tab Settings
$number_item = $this->getConfig('number_item',12);
$enable_animate_tab = $this->getConfig('enable_animate_tab');
$animation_speed = (int)$this->getConfig('animation_speed',"slow");
$collapsible = $this->getConfig('collapsible');
$cycle = $this->getConfig('cycle',1000);
$default_tab = (int)$this->getConfig('default_tab',0);
$transition_in = $this->getConfig('transition_in',"fadeIn");
$transition_in_easing = $this->getConfig('transition_in_easing',"swing");
$transition_out = $this->getConfig('transition_out',"fadeOut");
$transition_out_easing = $this->getConfig('transition_out_easing',"swing");
$event = $this->getConfig('event',"click");
$defaultTabId = '';


// Item Settings
$height_type = $this->getConfig('height_type');
$custom_item_height = (int)(str_replace("px","",$this->getConfig('custom_item_height', "")));
$show_name_single_line = $this->getConfig('show_name_single_line');
if($show_name_single_line){
    $classes .= ' single-line-name';
}


// OWL Carousel
$number_item_percolumn = (int)$this->getConfig('number_item_percolumn',200);
$large_max_items = (int)$this->getConfig('large_max_items',6);
$large_items = (int)$this->getConfig('large_items',5);
$portrait_items = (int)$this->getConfig('portrait_items',4);
$tablet_items = (int)$this->getConfig('tablet_items',4);
$tablet_small_items = (int)$this->getConfig('tablet_small_items',2);
$mobile_items = (int)$this->getConfig('mobile_items',1);
$autoplay = $this->getConfig('autoplay');
$autoplay_timeout = (int)$this->getConfig('autoplay_timeout',3000);
$dots = $this->getConfig('dots');
$nav = $this->getConfig('nav');
$nav_next = $this->getConfig('nav_next');
$nav_pre = $this->getConfig('nav_pre');
$rtl = $this->getConfig('rtl',false);
$loop = $this->getConfig('loop');
$ajaxBlockId = 'productlist-owlcarousel-'.$blockId;
// Convert collection to multiple row
// Default column
$column = 13;
$tabs = $this->getTabs();
  
        $collection = $this->getProductsBySource('except_featured');
        $_productCollection = [];
        $total = $collection->count();
        $tabs[0]['productCollection'] = $collection;
        $tabs[0]['productCount'] = $total;
        if($total == 0) unset($tabs[0]);

        $tabs[0]['id'] = str_replace('_','-','productlist-'.'latest'.'-'.rand().time());
        if(isset($tabs[0]['position']) && $default_tab && $tabs[0]['position'] == $default_tab){
            $defaultTabId = 'tab-'.$tabs[0]['id'];
        }

        $collection_featured = $this->getProductsBySource('featured');
        $total = $collection_featured->count();
        $tabs[1]['productCollection'] = $collection_featured;
        $tabs[1]['productCount'] = $total;
        $type= 'featured';
        if($total == 0) unset($tabs[1]);

        $tabs[1]['id'] = str_replace('_','-','productlist-'.'latest'.'-'.rand().time());
        if(isset($tabs[1]['position']) && $default_tab && $tabs[1]['position'] == $default_tab){
            $defaultTabId = 'tab-'.$tabs[1]['id'];
        }



$data = $this->getData();
?>

<!-- a -->


<header>
    <div class="container">
        <h1 class="logo"><strong>KALA & MANN</strong></h1>
         <?php if(count($tabs)>0){ ?>
            <?php
            $classTmp = '';
            if(!isset($tabs[1]['productCount']) && !isset($tabs[1]['productCount'])){
                // $classTmp = 'owl-carousel';
            } ?>
            <div class="owl-carousel" id="gallery1">
                <?php
                if(isset($tabs[1]['productCount']) && $tabs[1]['productCount']>0){
                    $collection = $tabs[1]['productCollection'];
                    ?>
                    <?php // Product List ?>
                    <?php
                    $data['collection'] = $collection;
                    echo $this->getProductHtml($data,'featured'); ?>
                    <?php } ?>
            </div>
                <?php } ?>

        <div class="social-buttons">
            <a href="#">
                <img src="<?php echo $block->getUrl("pub/media/img/")?>facebook.png">
            </a>
            <a href="#">
                <img src="<?php echo $block->getUrl("pub/media/img/")?>twitter.png">
            </a>
            <a href="#">
                <img src="<?php echo $block->getUrl("pub/media/img/")?>linkedin.png">
            </a>
            <a href="#">
                <img src="<?php echo $block->getUrl("pub/media/img/")?>instagram.png">
            </a>
            <a href="#">
                <img src="<?php echo $block->getUrl("pub/media/img/")?>pinterest.png">
            </a>
        </div>
    </div>
</header>


<div class="block" id="about">
    <div class="container about-us">
        
        <?php 
    echo $block->getLayout()
               ->createBlock('Magento\Cms\Block\Block')
               ->setBlockId('kasitoo-aboutus')
               ->toHtml();
?>
    </div>
</div>





<div class="block gallery">
    <div class="container">
        <h1 class="gallery-h1">Gallery</h1>
        <p class="subtitle">Discover all our artworks</p>
    <?php if(count($tabs)>0){ ?>
            <?php
            $classTmp = '';
            if(!isset($tabs[0]['productCount']) && !isset($tabs[0]['productCount'])){
            } ?>
            <div class="owl-carousel" id="gallery2"  >
                <?php
                if(isset($tabs[0]['productCount']) && $tabs[0]['productCount']>0){
                    $collection = $tabs[0]['productCollection'];
                    ?>
                    <?php // Product List ?>
                    <?php
                    $data['collection'] = $collection;
                    echo $this->getProductHtml($data,'except_featured'); ?>
                    <?php } ?>
                </div>

</div>
</div>


<script type="text/javascript">
    require([
        'jquery',
        'Ves_Productlist/js/animsition'
        ], function () {
                    jQuery(document).ready(function(){
                        jQuery('#gallery1').owlCarousel({
                            nav: true,
                            navText: ["←","→"],
                            loop:true,
                            items:1,
                            margin:0,
                            stagePadding:0,
                            smartSpeed:450,
                            autoHeight:true,
                            autoplay:true,
                            autoplayTimeout:4000,
                            autoplayHoverPause:true,
                            responsive:{
                                0:{

                                }
                            }
                        });
                        jQuery('#gallery2').owlCarousel({
                            nav: true,
                            navText: ["<span aria-label=\"Previous\">←</span>","<span aria-label=\"Next\">→</span>"],
                            items:2,
                            margin:50,
                            stagePadding:0,
                            smartSpeed:450,
                            center: true,
                            autoplay:false,
                            autoHeight:true,
                            responsive:{
                                0:{
                                    items:1,
                                    center: false,
                                    nav: false,
                                    margin:0,
                                },
                                600:{
                                    items:2
                                },
                                1000:{
                                    items:2
                                }
                            }
                        });
                        
                        jQuery(document).on('click', 'a[href^="#"]', function (event) {
                            event.preventDefault();
                            jQuery('#sidebarCollapse').click();

                            jQuery('html, body').animate({
                                scrollTop: jQuery(jQuery.attr(this, 'href')).offset().top
                            }, 500);
                        });
                        // jQuery('.columns').addClass('animsition');
                        jQuery('.page-wrapper').append('<div class="animsition-loading" style="display:none"></div>');
                        jQuery(".animsition").animsition({
                            
                            linkElement: '.animsition-link',
                            // e.g. linkElement: 'a:not([target="_blank"]):not([href^="#"])'
                            loading: true,
                            loadingParentElement: 'body', //animsition wrapper element
                            loadingClass: 'animsition-loading',
                            timeout: false,
                            timeoutCountdown: 1000,
                            onLoadEvent: true,
                            browser: [ 'animation-duration', '-webkit-animation-duration'],
                            // "browser" option allows you to disable the "animsition" in case the css property in the array is not supported by your browser.
                            // The default setting is to disable the "animsition" in a browser that does not support "animation-duration".
                            overlay : false,
                            overlayClass : 'animsition-overlay-slide',
                            overlayParentElement : 'body',
                            transition: function(url){ 
                                jQuery('.animsition-loading').show();
                                window.location.href = url; 
                            }
                          });








                    });

                        });
            </script>
    <?php } ?>
</div>