<?php
use Magento\Framework\App\Action\Action;
$_vesHelper = $this->helper('Ves\Productlist\Helper\Data');
$_imgHelper = $this->helper('Ves\Productlist\Helper\Image');
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$blockId = rand().time();
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$html = $classes = '';
$tabId = 'productlist-'.$blockId;

// General Settings
$widget_title = $this->getConfig('widget_title');
$addition_class = $this->getConfig('addition_class');
$cmsblock = $this->getConfig('cmsblock');
$pretext_html = $this->getConfig('pretext_html');
if($cmsblock === 'pretext_html'){
    $html = base64_decode($pretext_html);
}elseif($cmsblock!=''){
    $html = $this->getCmsBlockModel()->load($cmsblock)->getContent();
}
$html = $_vesHelper->filter($html);


// Tab Settings
$number_item = $this->getConfig('number_item',12);
$enable_animate_tab = $this->getConfig('enable_animate_tab');
$animation_speed = (int)$this->getConfig('animation_speed',"slow");
$collapsible = $this->getConfig('collapsible');
$cycle = $this->getConfig('cycle',1000);
$default_tab = (int)$this->getConfig('default_tab',0);
$transition_in = $this->getConfig('transition_in',"fadeIn");
$transition_in_easing = $this->getConfig('transition_in_easing',"swing");
$transition_out = $this->getConfig('transition_out',"fadeOut");
$transition_out_easing = $this->getConfig('transition_out_easing',"swing");
$event = $this->getConfig('event',"click");
$defaultTabId = '';


// Item Settings
$height_type = $this->getConfig('height_type');
$custom_item_height = (int)(str_replace("px","",$this->getConfig('custom_item_height', "")));
$show_name_single_line = $this->getConfig('show_name_single_line');
if($show_name_single_line){
    $classes .= ' single-line-name';
}


// OWL Carousel
$number_item_percolumn = (int)$this->getConfig('number_item_percolumn',200);
$large_max_items = (int)$this->getConfig('large_max_items',6);
$large_items = (int)$this->getConfig('large_items',5);
$portrait_items = (int)$this->getConfig('portrait_items',4);
$tablet_items = (int)$this->getConfig('tablet_items',4);
$tablet_small_items = (int)$this->getConfig('tablet_small_items',2);
$mobile_items = (int)$this->getConfig('mobile_items',1);
$autoplay = $this->getConfig('autoplay');
$autoplay_timeout = (int)$this->getConfig('autoplay_timeout',3000);
$dots = $this->getConfig('dots');
$nav = $this->getConfig('nav');
$nav_next = $this->getConfig('nav_next');
$nav_pre = $this->getConfig('nav_pre');
$rtl = $this->getConfig('rtl',false);
$loop = $this->getConfig('loop');
$ajaxBlockId = 'productlist-owlcarousel-'.$blockId;
// Convert collection to multiple row
// Default column
$column = 13;
$tabs = $this->getTabs();
foreach ($tabs as $k => $tab) {
    if(!$tab['ajax_type']){
        $collection = $this->getProductsBySource($tab['source_id']);
        $_productCollection = [];
        $total = $collection->count();
        
        $tabs[$k]['productCollection'] = $collection;
        $tabs[$k]['productCount'] = $total;
        if($total == 0) unset($tabs[$k]);
    }
    if(isset($tabs[$k])){
        $tabs[$k]['id'] = str_replace('_','-','productlist-'.$tab['source_id'].'-'.rand().time());
        if(isset($tabs[$k]['position']) && $default_tab && $tabs[$k]['position'] == $default_tab){
            $defaultTabId = 'tab-'.$tabs[$k]['id'];
        }
    }
}
$data = $this->getData();
?>

<!-- a -->

    <?php if(count($tabs)>0){ ?>
    
     
        
     
            <?php
            // $classTmp = 'owl-carousel';
            $classTmp = '';
            if(!isset($tabs[0]['productCount']) && !isset($tabs[0]['productCount'])){
                // $classTmp = 'owl-carousel';
            } ?>
            <div class="owl-carousel" id="gallery2"  >
                <?php
                if(isset($tabs[0]['productCount']) && $tabs[0]['productCount']>0){
                    $collection = $tabs[0]['productCollection'];
                    ?>
                    <?php // Product List ?>
                    <?php
                    $data['collection'] = $collection;
                    echo $this->getProductHtml($data); ?>
                    <?php } ?>
                </div>


        <!-- </div> -->


<script type="text/javascript">
    require([
        'jquery',
        ], function () {
                    jQuery('#sidebarCollapse').on('click', function () {
                        jQuery('#sidebar').toggleClass('active');
                    });

                    jQuery(document).ready(function(){
                        jQuery('#gallery1').owlCarousel({
                            nav: true,
                            navText: ["←","→"],
                            loop:true,
                            items:1,
                            margin:0,
                            stagePadding:0,
                            smartSpeed:450,
                            autoHeight:true,
                            autoplay:true,
                            autoplayTimeout:4000,
                            autoplayHoverPause:true,
                            responsive:{
                                0:{

                                }
                            }
                        });
                        jQuery('#gallery2').owlCarousel({
                            nav: true,
                            navText: ["<span aria-label=\"Previous\">←</span>","<span aria-label=\"Next\">→</span>"],
                            items:2,
                            margin:50,
                            stagePadding:0,
                            smartSpeed:450,
                            center: true,
                            autoplay:false,
                            autoHeight:true,
                            responsive:{
                                0:{
                                    items:1,
                                    center: false,
                                    nav: false,
                                    margin:0,
                                },
                                600:{
                                    items:2
                                },
                                1000:{
                                    items:2
                                }
                            }
                        });

                        jQuery(document).on('click', 'a[href^="#"]', function (event) {
                            event.preventDefault();
                            jQuery('#sidebarCollapse').click();

                            jQuery('html, body').animate({
                                scrollTop: $($.attr(this, 'href')).offset().top
                            }, 500);
                        });
                    });





                        });
            </script>
    <?php } ?>
</div>