<?php 
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$base_url = $storeManager->getStore()->getBaseUrl();
?>

<div class="product-backbutton d-none d-md-block col-md-4">
			<a href="<?php echo $base_url;?>" class="animsition-link"><i class="fa fa-angle-left product-backbutton-icon"></i></a>
</div>
<script type="text/javascript">
	require([
		'jquery',
		'Ves_Productlist/js/animsition'
		],function(){
		jQuery(document).ready(function(){
			jQuery('.columns').addClass('animsition');
			jQuery('.page-wrapper').append('<div class="animsition-loading" style="display:none"></div>');
			jQuery('#sidebarCollapse').on('click', function () {
                        jQuery('#sidebar').toggleClass('active');
                    });
			// jQuery(".animsition").animsition({
   //                          inClass: 'fade-in',
   //                          outClass: 'fade-out',
   //                          inDuration: 1500,
   //                          outDuration: 800,
   //                          linkElement: '.animsition-link',
   //                          // e.g. linkElement: 'a:not([target="_blank"]):not([href^="#"])'
   //                          loading: true,
   //                          // loadingParentElement: 'body', //animsition wrapper element
   //                          loadingClass: 'animsition-loading',
   //                          // loadingInner: '<img src="pub/media/img/Spin-1.2s-50px.svg" />',
   //                          timeout: false,
   //                          timeoutCountdown: 1000,
   //                          onLoadEvent: true,
   //                          browser: [ 'animation-duration', '-webkit-animation-duration'],
   //                          // "browser" option allows you to disable the "animsition" in case the css property in the array is not supported by your browser.
   //                          // The default setting is to disable the "animsition" in a browser that does not support "animation-duration".
   //                          overlay : false,
   //                          overlayClass : 'animsition-overlay-slide',
   //                          overlayParentElement : 'body',
   //                          transition: function(url){ 
   //                          	jQuery('.animsition-loading').show();
   //                          	window.location.href = url; 
   //                          }
   //                        });
		});
	});
</script>

