
<?php 
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');



$base_url = $storeManager->getStore()->getBaseUrl();
?>
<div class="logo_title_product">
	<div class=col-md-12">
	KALA & MANA</div>
</div>


<script type="text/javascript">
	require([
		'jquery'
		],function(){
		jQuery(document).ready(function(){
			jQuery('#sidebarCollapse').on('click', function () {
                        jQuery('#sidebar').toggleClass('active');
                    });

			
		});
	});
</script>

